apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels:
    app: frontend
spec:
  containers:
  - name: nginx-contianer
    image: counterapp:v5
    imagePullPolicy: Never
    ports:
    - containerPort: 80
